### ISSUE TITLE
Koohii is dead, along with the Windows .exe

### ISSUE THREAD

**Issue by eao** [kaegi/alass#2]
You were kind enough to share an .exe in the Koohii thread about this program, but that forum is now dead.  If you compiled another .exe for Windows users and put it in the releases then I think it would open up the application to a wider audience.  Feel free to close this issue if you don't want to do that for whatever reason.

**Comment by kaegi** [comment]
I'm going to upload an .exe file. Pretty big changes are coming: direct video-to-subtitle correction is now possible thanks to voice activity detection + significant performance improvements for long movies (<10s for all tested configurations). Once I've cleaned up all code on my machine, I will upload a release - you can expect the release within the next month.

I hope I'm able to set up a continuous integration pipeline that builds an .exe file automatically.

Thank you for watching aligner since the old Koohii-days :)

**Comment by kaegi** [comment]
The Dropbox link actually still works and is https://www.dropbox.com/s/iv21uk5dijfpnxi/aligner.exe?dl=1 for anyone who stumbles on this issue.

**Comment by pigoz** [comment]
> direct video-to-subtitle correction is now possible thanks to voice activity detection

Wow, that's really impressive. Well, I guess it's just Fourier transforms, but still :D

**Comment by kaegi** [comment]
Nope, this version can still handle splits like it can now (does not use FFT). There's a also a simpler version included without splits (also not using FFT), that terminates in about 0.1s even for large subtitles and is very accurate.

**Comment by kaegi** [comment]
Clarification: For the VAD it's using the WebRTC component (probably FFT in there). The algorithm itself does not use FFT like https://github.com/smacke/subsync (great project).

**Comment by pigoz** [comment]
> Clarification: For the VAD it's using the [WebRTC component](https://github.com/dpirch/libfvad) (probably FFT in there). The alignment algorithm itself does not use FFT like https://github.com/smacke/subsync (great project).

Yeah, I figured the alignment algorithm still uses dynamic programming. `libfvad` is super cool, didn't know something like that existed.

**Comment by kaegi** [comment]
The new version is now released with the promised capability to synchronize subtitles-to-videos! Since I'm mostly using Linux and only cross-compile to Windows, feedback on the new `alass` release is greatly appreciated. I tested it and everything seemed to work - but you never know...
