### ISSUE TITLE
Properly synced sub is "de-synced" - win

### ISSUE THREAD

**Issue by sharinganthief** [kaegi/alass#9]
Windows user, love the concept, already had some success, but i am writing a library "minifier" to convert all my files to mkv, srt to ass - with some netflix style formatting - and embed so you have one file per video entity.

I had what i thought was just a "too rough to be fixed" sub and downloaded a fresh set which matches the file perfectly. 
The idea would be since it was already correct, running it though the synchronizer would not be an issue, i would effectively just get the same sub back out.

The resultant subtitle is wildly out of sync.

in testing i have received two very similar messages regarding negative timing

warn: negative subtitles will therefore moved to the start of the subtitle file by default; pass '-n' or '--allow-negative-timestamps' to disable this behavior

warn: negative timestamps will be written to file, because you passed '-n' or '--allow-negative-timestamps'

So my second question i guess is, is there a way to not have the subtitles written with 0 or negative values, simply not modified?

**Comment by kaegi** [comment]
The warning about negative timestamps is from the "output stage" of alass since most subtitle formats do not specify how to encode negative timestamps.

This means the algorithm thinks that the subtitle gets somehow more optimal by de-syncing it in a specific way. I have already explained the tips to find more optimal alignment settings [here](https://github.com/kaegi/alass/issues/7):

  - it is probably caused by framerate guessing (try `--disable-fps-guessing`)
  - otherwise use `--no-split` or a higher `--split-penalty 30`

Please tell me whether that solved the problem.

**Comment by sharinganthief** [comment]
the `--disable-fps-guessing` did solve my issue for that file, thanks
